name: just_audio_vlc
description: Libvlc implementation of just_audio. This implementation is endorsed and therefore doesn't require a direct dependency.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dart_vlc: ^0.2.0
  flutter:
    sdk: flutter
  just_audio_platform_interface: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: just_audio
    platforms:
      windows:
        pluginClass: none
        dartPluginClass: JustAudioVlcPlugin
      linux:
        pluginClass: none
        dartPluginClass: JustAudioVlcPlugin
